/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A translation result containing the command and confidence */
export interface TranslationResult {
  /** The translated shell command */
  command: string
  /** Confidence score (0.0 to 1.0) */
  confidence: number
  /** Alternative commands if available */
  alternatives: Array<string>
  /** Explanation of what the command does */
  explanation: string
}
/** Create a new translator instance */
export declare function createTranslator(): LmshTranslator
/** Natural language to shell translator */
export declare class LmshTranslator {
  constructor()
  /** Translate natural language to a shell command */
  translate(input: string): TranslationResult
  /** Add a custom alias */
  addAlias(alias: string, command: string): void
  /** Get all aliases */
  getAliases(): Record<string, string>
  /** Translate using aliases first, then patterns */
  translateWithAliases(input: string): TranslationResult
}
